M48
; DRILL file {KiCad 9.0.7-1.fc43app1} date 2026-04-10T15:23:38+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-10T15:23:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-1.fc43app1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.800
%
G90
G05
T1
X128.85Y-79.145
X128.85Y-84.925
T2
X170.15Y-80.6
M30
